# Generated by Django 4.1.7 on 2023-05-02 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_date_add_alter_tip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 11, 50, 44, 595973)),
        ),
    ]
